services:
   openalex-topic-classification:
     image: colav/openalex-topic-classification:v1
     container_name: $OA_TOPICS_CONTAINER_NAME
     ports:
      - 8080:$OA_TOPICS_PORT
     environment:
       - OA_TOPICS_PORT=8080
       - OA_TOPICS_CONTAINER_NAME=openalex-topic-classification
       - OA_TOPICS_CPUS=16
       - OA_TOPICS_RAM=16G
       - OA_TOPICS_INTERNAL_NETWORK=false
       - TF_ENABLE_ONEDNN_OPTS=0
       - MODEL_SERVER_TIMEOUT=2600
       - MODEL_SERVER_WORKERS=1
     ulimits:
      memlock:
        soft: -1
        hard: -1
     restart: always
     networks:
      - oa_topics
     deploy:
      resources:
          limits:
            cpus: $OA_TOPICS_CPUS
            memory: $OA_TOPICS_RAM

networks:
  oa_topics:
    driver: bridge
    internal: $OA_TOPICS_INTERNAL_NETWORK
